### ISSUE TITLE
[Question] Finalise only classes that have implements/extends?

### ISSUE THREAD

**Issue by deoomen** [rectorphp/swiss-knife#10]
Hi!

Is there an option to only finalise classes that implement an interface or extend another class?

Like in `FinalizeClassesWithoutChildrenRector`.

```diff
-class FirstClass extends SecondClass
+final class FirstClass extends SecondClass
 {
 }

 class SecondClass
 {
 }

class ThirdClass
{
}
```

I don't want to change classes without extends/implements (`ThirdClass`).

**Comment by TomasVotruba** [comment]
Hi,

not at the moment. It could be an option `--exlude-interface`. 
Could you add it to the command to handle it?

**Comment by deoomen** [comment]
I tried:
```
vendor/bin/swiss-knife finalize-classes src --require-interface
```
but:
```
The "--require-interface" option does not exist.
```

**Comment by TomasVotruba** [comment]
We don't have that option.

Would you add it via PR?

**Comment by deoomen** [comment]
Oh, I misunderstood you, sorry.

I could try, but at the moment I have very little time after hours, so I don't know when it could be done.

Could you briefly describe what should be changed?

**Comment by TomasVotruba** [comment]
The option must be added in the configure() method,
then processed in execute() method: https://github.com/rectorphp/swiss-knife/blob/main/src/Command/FinalizeClassesCommand.php#L38-L56

Feel free to send PR when your free :+1: Thank you 

Closing as idea moved to PR phase
