### ISSUE TITLE
Finalized a class that was mocked by mockery

### ISSUE THREAD

**Issue by RedsCoyote** [rectorphp/swiss-knife#24]
If you use Mockery (https://github.com/mockery/mockery) library for mocking, command `vendor/bin/swiss-knife finalize-classes [folder] --skip-mocked` will finalize mocked classes

**Comment by TomasVotruba** [comment]
Mocked classes should not be unfinalized just for the tools' sake.

There is a better way:
https://tomasvotruba.com/blog/2019/03/28/how-to-mock-final-classes-in-phpunit

**Comment by RedsCoyote** [comment]
A Swiss knife with a single blade for phpunuit mocks looks weird. Throwing away a popular testing framework like Mockery is your right. OK
