### ISSUE TITLE
Constant can't be declared private or protected in interface

### ISSUE THREAD

**Issue by alexndlm** [rectorphp/swiss-knife#34]
That's what says PHPMD. It will be nice to skip checking consts on interfaces.

**Comment by TomasVotruba** [comment]
Indeed :+1:  https://3v4l.org/1h8D0


What result do you get with this command on interfaces?

**Comment by alexndlm** [comment]
Like this.
<img alt="Снимок экрана 2024-06-30 в 13 03 44" src="https://github.com/rectorphp/swiss-knife/assets/6824784/d74e192d-8efd-442b-9203-bb6cf77b2dd2" width="100%">
<p>&nbsp;</p>
<img alt="Снимок экрана 2024-06-30 в 13 04 03" src="https://github.com/rectorphp/swiss-knife/assets/6824784/5fcb40aa-be3d-43fe-bac0-1376484c62cb" width="100%">

**Comment by TomasVotruba** [comment]
Could you send PR? 🙏

**Comment by alexndlm** [comment]
Maybe - https://github.com/rectorphp/swiss-knife/pull/35?

**Comment by TomasVotruba** [comment]
Most likely fixed in https://github.com/rectorphp/swiss-knife/pull/44 :+1:
