### ISSUE TITLE
Mockery

### ISSUE THREAD

**Issue by ruudk** [rectorphp/swiss-knife#36]
When using `--skip-mocked` it does not take into account Mockery.

**Comment by TomasVotruba** [comment]
We only support PHPUnit now.

Other testing frameworks need extension here: https://github.com/rectorphp/swiss-knife/blob/b2c4ffe818c3fa329ba4df27e490c7812a8fddce/src/PhpParser/NodeVisitor/MockedClassNameCollectingNodeVisitor.php#L24-L36
