### ISSUE TITLE
[find-multi-classes] Ambiguous class

### ISSUE THREAD

**Issue by atournayre** [rectorphp/swiss-knife#42]
I have 2 files :

*   /var/www/symfony/src/Domain/Model/Document/Document.php
*   /var/www/symfony/src/Domain/Services/Document/Document.php

```php
// /var/www/symfony/src/Domain/Model/Document/Document.php

<?php

namespace Neo\Domain\Model\Document;

class Document {}
```

and

```
// /var/www/symfony/src/Domain/Services/Document/Document.php

<?php

namespace Neo\Domain\Services\Document;

class Document {}
```

I have the following error

> In RobotLoader.php line 211:  
> Ambiguous class Neo\\Document resolution; defined in /var/www/symfony/src/Domain/Model/Document/Document.php and in /var/www/symfony/src/Domain/Services/Document/Document.php.    
> find-multi-classes \[--exclude-path EXCLUDE-PATH\] \[--\] \<sources>...

I'm OK that names are ambiguous but classes resides in different folders and namespaces.

So why is this error happening?

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting.

This looks like a bug in nette/robot-loader. Could you report it there with minimal reproducer?

**Comment by atournayre** [comment]
Sure, here it is https://github.com/nette/robot-loader/issues/35

**Comment by TomasVotruba** [comment]
Thanks :+1:
