### ISSUE TITLE
Files in scan directory root gets additional postfix \ in their namespace

### ISSUE THREAD

**Issue by RafalSalwa** [rectorphp/swiss-knife#9]
Hi, two things related to swiss-knife
1. Namespace root files get additional backslash
2. On second run, swiss-knife throws a syntax error

How to reproduce:
command:
`
vendor/bin/swiss-knife namespace-to-psr-4 src --namespace-root "App\\"
`

run in symfony project (6.3) on src directory with following structure
```
src
  Controller/
  Entity/
  Repository/
  Kernel.php
```

Fixer works flawlessly for every file inside directories :=)
Unfortunately files in scan directory root are getting App\ namespace with additional backslash.

```PHP
declare(strict_types=1);

namespace App\;

use Symfony\Bundle\FrameworkBundle\Kernel\MicroKernelTrait;
use Symfony\Component\HttpKernel\Kernel as BaseKernel;

class Kernel extends BaseKernel
{
    use MicroKernelTrait;
}
```

after running swiss-knife and then paraller-lint linter for example, i got this error:
![image](https://github.com/rectorphp/swiss-knife/assets/26059025/a8470efa-5d88-4cbc-b9dc-1d391d9f94d2)

Also in second run You will get error:

![image](https://github.com/rectorphp/swiss-knife/assets/26059025/a0e6d8f3-1d72-4ed7-822d-e0d8c8f04f04)

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting.  This package is in its early development, so testing like your is very important to us.

Could you send us a PR with fix?

**Comment by RafalSalwa** [comment]
yes, within this week i will sit and help with this one:)

**Comment by TomasVotruba** [comment]
Closing for lack of feedback. Thanks for understanding :+1: 

Feel free to send PR next time, so we can merge this easily. Thanks
